version: '3'
services:
  wedding-plan-database-local:
    image: "postgres:15-alpine"
    hostname: wedding-plan-database-local
    container_name: wedding-plan-database-local
    env_file:
      - config/config_db_local.env
    volumes:
      - ./sql/01-wedding-plan-schema.sql:/docker-entrypoint-initdb.d/01-pg-schema.sql
      - ./sql/02-blog-posts.sql:/docker-entrypoint-initdb.d/02-blog-posts.sql
      - wedding-plan-database-local:/var/lib/postgresql/data

    ports:
      - "5492:5432"
    networks:
      local_sandbox:
        ipv4_address: 172.27.0.20

    labels:
      wedding.plan.local: "database"

  wedding-plan-api-local:
    build:
      context: ./src/app/
      dockerfile: Dockerfile.api_local
    hostname: wedding-plan-api-local
    container_name: wedding-plan-api-local
    env_file:
      - config/config_api_local.env
    ports:
      - 8002:8000
    develop:
      watch:
        - action: sync
          path: ./src/app/
          target: /app/

    networks:
      local_sandbox:
        ipv4_address: 172.27.0.10
    labels:
      wedding.plan.local: "api"
    tty: true

  wedding-plan-nginx-local:
    build: ./nginx/local_watch/
    hostname: wedding-plan-nginx-local
    container_name: wedding-plan-nginx-local
    ports:
      - "8060:8050"
    depends_on:
      - wedding-plan-api-local
    networks:
      local_sandbox:
        ipv4_address: 172.27.0.13
    labels:
      wedding.plan: "nginx"
    tty: true

volumes:
  wedding-plan-database-local:
    driver: local

networks:
  local_sandbox:
    external: true
    name: local_sandbox
