FROM python:3.10.0-slim as base 


RUN apt-get clean \
    && apt-get -y update \
    && apt-get -y install --no-install-recommends python3-dev libaio1 wget \
    unzip build-essential libpq-dev uwsgi-plugin-python3\
    gcc iputils-ping \
    && ln -fs /usr/share/zoneinfo/Europe/Athens /etc/localtime \
    && dpkg-reconfigure -f noninteractive tzdata \
    && rm -rf /var/lib/apt/lists/*


FROM base as builder

RUN mkdir /install
WORKDIR /install

COPY requirements.txt /requirements.txt


WORKDIR /install
RUN pip install --upgrade pip && pip3 install -r /requirements.txt --root /install/ --prefer-binary --no-warn-script-location


FROM base

COPY --from=builder /install /install 
COPY . /app

RUN cp -r /install/usr/local/bin/* /usr/local/bin/ && \
    cp -r /install/usr/local/lib/python3.10/site-packages/* /usr/local/lib/python3.10/site-packages


WORKDIR /app

ENTRYPOINT ["/bin/bash" , "/app/entrypoint_prod.sh"]